

#include "FreeRTOS.h"
#include "task.h"


#include "em_device.h"
#include "em_system.h"
#include "em_chip.h"
#include "em_gpio.h"
#include "em_cmu.h"
#include "em_core.h"
//#include "gpiointerrupt.h"
/*-----------------------------------------------------------*/

/*Definations */
const uint16_t LED0 = 2;
const uint16_t LED1 = 3;

const uint16_t PB1 = 9;
const uint16_t PB2 = 10;

/*-----------------------------------------------------------*/

static void prvSetupHardware( void );
void GPIOInitialize( void );
void vBlinky1( void *pvParameters);
void vBlinky2();
void GPIO_ODD_IRQHandler( void );

void xTimerCreateTimerTask(void);



/*-----------------------------------------------------------*/

int main( void )
{
	
	/* Configure the hardware ready to run the demo. */
	prvSetupHardware();
	
	xTaskCreate(vBlinky1, "Blinky1", 1, NULL, NULL, NULL);
	
	vTaskStartScheduler();
	
	while(1) {
		
		}
	
	
}
/*-----------------------------------------------------------*/

static void prvSetupHardware( void )
{
	/* Library initialisation routines. */
	CHIP_Init();
	SystemInit();
	GPIOInitialize();
	

}

/*-----------------------------------------------------------*/

void GPIOInitialize( void )	{
	
	//Enable Clock For GPIO
	CMU_ClockEnable(cmuClock_GPIO, true);
	
	//Set GPIO PIns PE2 and PE3 as Output Leds
	GPIO_PinModeSet( gpioPortE, LED0, gpioModePushPull, 1);
	GPIO_PinModeSet( gpioPortE, LED1, gpioModePushPull, 1);
	
	//Set GPIO PB9, PB10 as Button Inputs
	GPIO_PinModeSet( gpioPortB, PB1, gpioModeInput, 1);
	GPIO_PinModeSet( gpioPortB, PB2, gpioModeInput, 1);
	
	//Make PE2 and PE3 Low
	GPIO_PinOutClear( gpioPortE, LED0);
	GPIO_PinOutClear( gpioPortE, LED1);
	
	//Interrupt Enable for PB1(9)
	NVIC_ClearPendingIRQ(GPIO_ODD_IRQn);
	NVIC_EnableIRQ(GPIO_ODD_IRQn);
	
	//Intterrupt Enable for PB2(10)
//	NVIC_ClearPendingIRQ(GPIO_EVEN_IRQn);
//	NVIC_EnableIRQ(GPIO_EVEN_IRQn);
	
	//Set interrupt to rising edge for PB1(9)
	GPIO_IntConfig(gpioPortB, PB1, false, true, true);
//	GPIO_IntConfig(gpioPortB, PB2, false, true, true);
}	


/*-----------------------------------------------------------*/

void vBlinky1( void *pvParameters ) {
	const char *pcTaskName = "Blinky us running\r\n";
	GPIO_PinOutToggle( gpioPortE, LED0);
	vTaskDelete(NULL);
}


void vBlinky2() {
	const char *pcTaskName = "Blinky us running\r\n";
	GPIO_PinOutToggle( gpioPortE, LED1);
	vTaskDelete(NULL);
}



void GPIO_ODD_IRQHandler( void ) {
		
		//Cleared Interrupt generated by PB1(9)
		GPIO_IntClear(0x200);
		xTaskCreate(vBlinky1, "Blinky1", 1, NULL, NULL, NULL);

}


void xTimerCreateTimerTask(void){}
	