

#include "FreeRTOS.h"
#include "task.h"


#include "ITM.h"
#include "em_device.h"
#include "em_system.h"
#include "em_chip.h"
#include "em_gpio.h"
#include "em_cmu.h"
#include "em_core.h"


/*-----------------------------------------------------------*/

/*Definations */
const uint16_t LED0 = 2;
const uint16_t LED1 = 3;

const uint16_t PB1 = 9;
const uint16_t PB2 = 10;

//Constant Values for Using Internal Temperature ADC
const float thermometerGradient = -6.3;
#define thermCalTemp = ((DEVINFO->CAL & _DEVINFO_CAL_TEMP_MASK) >> _DEVINFO_CAL_TEMP_SHIFT);
#define thermCalValue = ((DEVINFO->ADC0CAL2 & _DEVINFO_ADC0CAL2_TEMP1V25_MASK) >> _DEVINFO_ADC0CAL2_TEMP1V25_SHIFT);

//uint16_t counter = 0;
/*-----------------------------------------------------------*/

static void prvSetupHardware( void );

void GPIO_Setup( void );
void ADC_Setup( void );

void vBlinky1( void *pvParameters );
void vBlinky2( void *pvParameters );
void GPIO_ODD_IRQHandler( void );

void xTimerCreateTimerTask(void);



/*-----------------------------------------------------------*/

int main( void )
{
	
	/* Configure the hardware ready to run the demo. */
	prvSetupHardware();
	
	vTaskStartScheduler();
	
	while(1) {
		
		}
	
	
}
/*-----------------------------------------------------------*/

static void prvSetupHardware( void )
{
	CHIP_Init();
	
	SystemCoreClockUpdate();
	
	SWO_Setup();				//Serial Wire Debug Out Setup
	
	GPIO_Setup();
	
	ADC_Setup();
	
//	vTaskDelay(1000);

}

/*-----------------------------------------------------------*/

void GPIO_Setup( void )	{
	
	//Enable Clock For GPIO
	CMU_ClockEnable(cmuClock_GPIO, true);
	
	//Set GPIO PIns PE2 and PE3 as Output Leds
	GPIO_PinModeSet( gpioPortE, LED0, gpioModePushPull, 1);
	GPIO_PinModeSet( gpioPortE, LED1, gpioModePushPull, 1);
	
	//Set GPIO PB9, PB10 as Button Inputs
	GPIO_PinModeSet( gpioPortB, PB1, gpioModeInput, 1);
	GPIO_PinModeSet( gpioPortB, PB2, gpioModeInput, 1);
	
	//Make PE2 and PE3 Low
	GPIO_PinOutClear( gpioPortE, LED0);
	GPIO_PinOutClear( gpioPortE, LED1);
	
	//Interrupt Enable for PB1(9)
	NVIC_ClearPendingIRQ(GPIO_ODD_IRQn);
	NVIC_EnableIRQ(GPIO_ODD_IRQn);
	
	//Intterrupt Enable for PB2(10)
//	NVIC_ClearPendingIRQ(GPIO_EVEN_IRQn);
//	NVIC_EnableIRQ(GPIO_EVEN_IRQn);
	
	//Set interrupt to rising edge for PB1(9)
	GPIO_IntConfig(gpioPortB, PB1, false, true, true);
//	GPIO_IntConfig(gpioPortB, PB2, false, true, true);
}	

void ADC_Setup()	{
	
	//Enable Clock for ADC0
	CMU_ClockEnable(cmuClock_ADC0, true);
	
	
}

/*-----------------------------------------------------------*/

void vBlinky1( void *pvParameters ) {
//	const char *pcTaskName = pvParameters;
	
	GPIO_PinOutToggle( gpioPortE, LED0);
	
	itmPrintln(pvParameters);
		
	vTaskDelay(100);
	
	vTaskDelete(NULL);
}

void vBlinky2( void *pvParameters ) {
//	const char *pcTaskName = pvParameters;
	while(1) {
		GPIO_PinOutToggle( gpioPortE, LED1);
		vTaskDelay(1000);
	}
//	vTaskDelete(NULL);
}

void GPIO_ODD_IRQHandler( void ) {
		
		//Cleared Interrupt generated by PB1(9)
		GPIO_IntClear(0x200);
	
		xTaskCreate(vBlinky1, "Blinky1", 1000, "Led0 Tooggled", 1, NULL);

}

void xTimerCreateTimerTask(void){
}






	